const data = [
  {
    Número: "INC0194887",
    Aberto: "09/02/2024ﾠ17:15:47",
    Atualizadoﾠem: "03/05/2024ﾠ14:34:26",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "Adapt",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Lentidãoﾠsistema",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "INC0201867",
    Aberto: "22/03/2024ﾠ08:08:10",
    Atualizadoﾠem: "02/05/2024ﾠ14:40:15",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "SistemaﾠLabware",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Lentidãoﾠsistema",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "INC0204817",
    Aberto: "16/04/2024ﾠ13:35:32",
    Atualizadoﾠem: "03/05/2024ﾠ14:54:03",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "HCA",
    QualificaçãoﾠSintoma: "Download",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "Lentidãoﾠsistema",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "INC0205119",
    Aberto: "18/04/2024ﾠ07:17:26",
    Atualizadoﾠem: "02/05/2024ﾠ12:29:14",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "Lakos",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Lentidãoﾠsistema",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "INC0208361",
    Aberto: "02/05/2024ﾠ11:47:19",
    Atualizadoﾠem: "02/05/2024ﾠ13:29:23",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "OutrosﾠSistemas",
    QualificaçãoﾠSintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N1-NÃO SAP",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "ImpressoraﾠNãoﾠImprime",
    ComentáriosﾠVisiveisﾠ: "Sim,ﾠsomenteﾠemﾠminhaﾠmaquinaﾠnãoﾠimprimeﾠ",
    Resolução: "Realizadoﾠinstalçãoﾠdriverﾠimpressora.",
  },
  {
    Número: "INC0208388",
    Aberto: "02/05/2024ﾠ16:59:33",
    Atualizadoﾠem: "02/05/2024ﾠ17:49:39",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "Genteﾠ&ﾠGestão",
    Grupoﾠdeﾠatribuição: "N1-NÃO SAP",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Sistemaﾠnãoﾠabreﾠ",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "TASK0900023",
    Aberto: "19/02/2024ﾠ08:16:45",
    Atualizadoﾠem: "01/05/2024ﾠ17:00:04",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AlteraçãoﾠdeﾠPerfil",
    Sintoma: "Manutençãoﾠdeﾠtransaçãoﾠeﾠobjeto",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS-SAP",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ17:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Incluirﾠperfilﾠespelho",
    ComentáriosﾠVisiveisﾠ: "UsarﾠperfilﾠespelhoﾠXXXXXXX",
    Resolução: "Realizadoﾠconformeﾠsolicitadoﾠoﾠespelhamentoﾠdoﾠperfilﾠ",
  },
  {
    Número: "TASK0900593",
    Aberto: "19/02/2024ﾠ13:14:10",
    Atualizadoﾠem: "01/05/2024ﾠ11:00:05",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AlteraçãoﾠdeﾠPerfil",
    Sintoma: "TrocaﾠdeﾠPerfil",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS-SAP",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "2ﾠ-ﾠMédio",
    Encerrado: "01/05/2024ﾠ11:00:05",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Trocaﾠdeﾠpefil",
    ComentáriosﾠVisiveisﾠ: "UsarﾠperfilﾠespelhoﾠXXXXXXX",
    Resolução: "Realizadoﾠconformeﾠsolicitadoﾠoﾠespelhamentoﾠdoﾠperfilﾠ",
  },
  {
    Número: "TASK0902990",
    Aberto: "21/02/2024ﾠ15:57:24",
    Atualizadoﾠem: "01/05/2024ﾠ18:00:04",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "LiberaçãoﾠdeﾠAcesso",
    Sintoma: "CriaçãoﾠdeﾠAcesso",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-OUTROS",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Criarﾠusuárioﾠdeﾠredeﾠ",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Usuárioﾠdeﾠredeﾠcriadoﾠeﾠenviadoﾠosﾠdadosﾠaoﾠgestorﾠimediato",
  },
  {
    Número: "TASK0912173",
    Aberto: "05/03/2024ﾠ16:55:51",
    Atualizadoﾠem: "03/05/2024ﾠ16:17:38",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "FuncionalﾠSAP",
    SubcategoriaﾠRelatório: "Solicitação",
    Sintoma: "AnáliseﾠSAP",
    QualificaçãoﾠSintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N1-SAP",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "4ﾠ-ﾠPlanejamento",
    Encerrado: "03/05/2024ﾠ16:17:38",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "ImpressoraﾠNãoﾠImprime",
    ComentáriosﾠVisiveisﾠ: "Não,ﾠestamosﾠsemﾠenergiaﾠnoﾠlocal",
    Resolução: "Realizadoﾠacionamentoﾠtimeﾠdeﾠfacilitesﾠlocal.",
  },
  {
    Número: "TASK0919208",
    Aberto: "14/03/2024ﾠ18:18:18",
    Atualizadoﾠem: "01/05/2024ﾠ18:00:40",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AlteraçãoﾠdeﾠPerfil",
    Sintoma: "OutrasﾠmanutençõesﾠdeﾠPerfil",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-OUTROS",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ18:00:40",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Incluirﾠperfilﾠespelho",
    ComentáriosﾠVisiveisﾠ: "UsarﾠperfilﾠespelhoﾠXXXXXXX",
    Resolução: "Realizadoﾠconformeﾠsolicitadoﾠoﾠespelhamentoﾠdoﾠperfilﾠ",
  },
  {
    Número: "TASK0926414",
    Aberto: "25/03/2024ﾠ17:17:59",
    Atualizadoﾠem: "01/05/2024ﾠ16:00:04",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "SolicitaçãoﾠdeﾠEquipamento",
    Sintoma: "ColaboradorﾠInterno",
    QualificaçãoﾠSintoma: "CapitaisﾠeﾠRegiõesﾠMetropolitanas",
    Grupoﾠdeﾠatribuição: "N2-FS-CA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ16:00:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "SolicitaçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "Equipamentosﾠliberadosﾠparaﾠentrega",
    Resolução: "Equipamentosﾠentregueﾠeﾠtermosﾠassinados",
  },
  {
    Número: "TASK0928474",
    Aberto: "28/03/2024ﾠ09:31:03",
    Atualizadoﾠem: "02/05/2024ﾠ09:08:05",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AtualizaçãoﾠdeﾠAcesso",
    Sintoma: "AtualizaçãoﾠdeﾠdadosﾠcadastraisﾠnaﾠBU",
    Grupoﾠdeﾠatribuição: "N1-OUTROS",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ09:08:06",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "AtualizaçãoﾠdeﾠAcesso",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Usuárioﾠdeﾠredeﾠcriadoﾠeﾠenviadoﾠosﾠdadosﾠaoﾠgestorﾠimediato",
  },
  {
    Número: "TASK0929053",
    Aberto: "28/03/2024ﾠ17:23:31",
    Atualizadoﾠem: "03/05/2024ﾠ08:41:16",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "SistemasﾠSAP",
    SubcategoriaﾠRelatório: "SuporteﾠFuncional",
    Sintoma: "Analise",
    QualificaçãoﾠSintoma: "OrdemﾠdeﾠProdução",
    Grupoﾠdeﾠatribuição: "N1-SAP",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "2ﾠ-ﾠMédio",
    Encerrado: "03/05/2024ﾠ08:41:17",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "SuporteﾠFuncional",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0931383",
    Aberto: "02/04/2024ﾠ13:05:46",
    Atualizadoﾠem: "02/05/2024ﾠ10:41:16",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "Nugenesis",
    Sintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "22/04/2024ﾠ15:05:12",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Sistemaﾠlentoﾠ",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0933095",
    Aberto: "04/04/2024ﾠ10:37:29",
    Atualizadoﾠem: "01/05/2024ﾠ13:00:42",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "TrocaﾠdeﾠEquipamento",
    Sintoma: "ColaboradorﾠExterno",
    QualificaçãoﾠSintoma: "Acimaﾠdeﾠ300Km",
    Grupoﾠdeﾠatribuição: "N2-FS-EX",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ13:00:42",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "TrocaﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "Equipamentosﾠliberadosﾠparaﾠentrega",
    Resolução: "Equipamentosﾠentregueﾠeﾠtermosﾠassinados",
  },
  {
    Número: "TASK0933890",
    Aberto: "05/04/2024ﾠ09:45:04",
    Atualizadoﾠem: "03/05/2024ﾠ09:42:44",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "CriarﾠPerfilﾠSAP",
    Sintoma: "CriarﾠperfilﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-SAP",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ09:42:44",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "CriarﾠPerfilﾠSAP",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução:
      "Ralizadoﾠaﾠcriaçãoﾠdoﾠacesso,ﾠenviadoﾠaoﾠgestorﾠimediatoﾠasﾠinformações.",
  },
  {
    Número: "TASK0935862",
    Aberto: "09/04/2024ﾠ09:32:28",
    Atualizadoﾠem: "02/05/2024ﾠ14:22:32",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "ConfiguraçãoﾠdeﾠEquipamento",
    Sintoma: "ConfiguraçãoﾠdeﾠEquipamento",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ14:22:33",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "ConfiguraçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "informarﾠmelhorﾠhorárioﾠparaﾠatendimentoﾠ",
    Resolução: "Realizadoﾠaﾠconfiguraçãoﾠdoﾠsmartphoneﾠconformeﾠsolicitado",
  },
  {
    Número: "TASK0937918",
    Aberto: "11/04/2024ﾠ12:02:32",
    Atualizadoﾠem: "01/05/2024ﾠ10:02:12",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "DevoluçãoﾠdeﾠEquipamento",
    Sintoma: "ColaboradorﾠInterno",
    QualificaçãoﾠSintoma: "CapitaisﾠeﾠRegiõesﾠMetropolitanas",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ10:02:12",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "DevoluçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠentregaﾠdosﾠequipamentos",
    Resolução: "Equipamentosﾠdevolvidosﾠaoﾠestoqueﾠlocalﾠ",
  },
  {
    Número: "TASK0939623",
    Aberto: "15/04/2024ﾠ10:39:31",
    Atualizadoﾠem: "01/05/2024ﾠ11:02:04",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "ServiçosﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Infraestruturaﾠ-ﾠSoluções",
    Sintoma: "Aquisiçãoﾠ/ﾠRenovaçãoﾠdeﾠAplicativo",
    Grupoﾠdeﾠatribuição: "N1-OUTROS",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ11:02:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Solicitoﾠnovoﾠpontoﾠdeﾠrede",
    ComentáriosﾠVisiveisﾠ: "Aguardandoﾠpassagemﾠdoﾠcabeamento",
    Resolução: "Pontosﾠcriadosﾠeﾠativados",
  },
  {
    Número: "TASK0942133",
    Aberto: "17/04/2024ﾠ18:12:59",
    Atualizadoﾠem: "01/05/2024ﾠ10:02:56",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Sistemas",
    SubcategoriaﾠRelatório: "Admissão",
    Sintoma: "Admissão",
    Grupoﾠdeﾠatribuição: "N1-OUTROS",
    Categoria: "ServiceﾠDesk",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ10:02:56",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Criarﾠusuárioﾠdeﾠredeﾠ",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Usuárioﾠdeﾠredeﾠcriadoﾠeﾠenviadoﾠosﾠdadosﾠaoﾠgestorﾠimediato",
  },
  {
    Número: "TASK0944627",
    Aberto: "22/04/2024ﾠ12:12:06",
    Atualizadoﾠem: "02/05/2024ﾠ19:54:09",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "ProrrogaçãoﾠdeﾠAcessos",
    Sintoma: "ProrrogaçãoﾠdeﾠAcessosﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS-SAP",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ19:54:09",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "ProrrogaçãoﾠdeﾠAcessos",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Realizadoﾠaﾠprorrogaçãoﾠdosﾠacessosﾠconformeﾠsolicitado",
  },
  {
    Número: "TASK0944775",
    Aberto: "22/04/2024ﾠ14:25:11",
    Atualizadoﾠem: "01/05/2024ﾠ14:03:05",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "EmpréstimoﾠdeﾠEquipamento",
    Sintoma: "EmpréstimoﾠdeﾠEquipamento",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ14:03:05",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "EmpréstimoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "RetirarﾠequipamentoﾠjuntoﾠaoﾠtimeﾠdeﾠFieldﾠService",
    Resolução: "Equipamentoﾠentregueﾠconformeﾠtermoﾠassinadoﾠeﾠanexado",
  },
  {
    Número: "TASK0945016",
    Aberto: "22/04/2024ﾠ16:39:18",
    Atualizadoﾠem: "03/05/2024ﾠ09:14:25",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AlteraçãoﾠdeﾠPerfil",
    Sintoma: "RemediaçãoﾠSolicitadasﾠporﾠControlesﾠInternosﾠ(CI)",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS-SAP",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ09:14:25",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "AlteraçãoﾠdeﾠPerfil",
    ComentáriosﾠVisiveisﾠ: "UsarﾠperfilﾠespelhoﾠXXXXXXX",
    Resolução: "Realizadoﾠconformeﾠsolicitadoﾠoﾠespelhamentoﾠdoﾠperfilﾠ",
  },
  {
    Número: "TASK0945485",
    Aberto: "23/04/2024ﾠ10:20:43",
    Atualizadoﾠem: "03/05/2024ﾠ11:11:47",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "SuporteﾠAcessos",
    Sintoma: "AnáliseﾠdeﾠusuáriosﾠAtivosﾠ/ﾠInativos",
    QualificaçãoﾠSintoma: "SistemaﾠNãoﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ11:11:47",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "SuporteﾠAcessos",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Usuárioﾠdeﾠredeﾠcriadoﾠeﾠenviadoﾠosﾠdadosﾠaoﾠgestorﾠimediato",
  },
  {
    Número: "TASK0946570",
    Aberto: "24/04/2024ﾠ11:33:29",
    Atualizadoﾠem: "01/05/2024ﾠ10:05:04",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "OutrasﾠSolicitações",
    SubcategoriaﾠRelatório: "OutrasﾠSolicitações",
    Sintoma: "Dúvida",
    QualificaçãoﾠSintoma: "Informação",
    Grupoﾠdeﾠatribuição: "TELEFONIA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ10:05:04",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "ConfiguraçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "informarﾠmelhorﾠhorárioﾠparaﾠatendimentoﾠ",
    Resolução: "Realizadoﾠaﾠconfiguraçãoﾠdoﾠsmartphoneﾠconformeﾠsolicitado",
  },
  {
    Número: "TASK0946697",
    Aberto: "24/04/2024ﾠ13:23:11",
    Atualizadoﾠem: "01/05/2024ﾠ12:06:46",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "ManutençãoﾠdeﾠEquipamentoﾠLocado",
    Sintoma: "ManutençãoﾠdeﾠEquipamentoﾠLocado",
    QualificaçãoﾠSintoma: "Simpress",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ12:06:46",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "ManutençãoﾠdeﾠEquipamentoﾠLocado",
    ComentáriosﾠVisiveisﾠ: "Trocarﾠcarcaçaﾠ",
    Resolução: "Realizadoﾠaﾠtrocaﾠdaﾠcarcaçaﾠ",
  },
  {
    Número: "TASK0946794",
    Aberto: "24/04/2024ﾠ14:44:00",
    Atualizadoﾠem: "01/05/2024ﾠ18:02:03",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "Reset/DesbloqueioﾠdeﾠSenha",
    Sintoma: "Reset/DesbloqueioﾠdeﾠSenhaﾠdeﾠSistemas",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "1ﾠ-ﾠAlto",
    Encerrado: "01/05/2024ﾠ18:02:03",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "Reset/DesbloqueioﾠdeﾠSenha",
    ComentáriosﾠVisiveisﾠ: "Informarﾠosﾠdadosﾠabaixo",
    Resolução: "Realizadoﾠdesbloqueioﾠdaﾠsenhaﾠdeﾠrede",
  },
  {
    Número: "TASK0947172",
    Aberto: "25/04/2024ﾠ08:46:11",
    Atualizadoﾠem: "02/05/2024ﾠ15:37:36",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "DelegaçãoﾠdeﾠAprovações",
    Sintoma: "DelegaçãoﾠdeﾠAprovações",
    QualificaçãoﾠSintoma: "SemﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ15:37:37",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "TrocaﾠdeﾠAcessos",
    ComentáriosﾠVisiveisﾠ: "UsarﾠperfilﾠespelhoﾠXXXXXXX",
    Resolução: "Realizadoﾠconformeﾠsolicitadoﾠoﾠespelhamentoﾠdoﾠperfilﾠ",
  },
  {
    Número: "TASK0947321",
    Aberto: "25/04/2024ﾠ10:26:02",
    Atualizadoﾠem: "01/05/2024ﾠ17:04:12",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "DMDocs",
    Sintoma: "Dúvida",
    QualificaçãoﾠSintoma: "Informação",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ17:04:12",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0947870",
    Aberto: "25/04/2024ﾠ18:02:24",
    Atualizadoﾠem: "01/05/2024ﾠ10:07:52",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "AtualizaçãoﾠdeﾠAcesso",
    Sintoma: "AtualizaçãoﾠdeﾠAcesso",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ10:07:52",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "AtualizaçãoﾠdeﾠAcesso",
    ComentáriosﾠVisiveisﾠ: "PorﾠfavorﾠliberarﾠacessoﾠaﾠpastaﾠXXXXXX",
    Resolução: "AcessoﾠliberadoﾠdeﾠleituraﾠnaﾠpastaﾠXXXXXXX",
  },
  {
    Número: "TASK0947940",
    Aberto: "26/04/2024ﾠ07:37:03",
    Atualizadoﾠem: "03/05/2024ﾠ11:51:07",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "SistemaﾠLabware",
    Sintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ11:51:07",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0948052",
    Aberto: "26/04/2024ﾠ09:46:43",
    Atualizadoﾠem: "01/05/2024ﾠ11:07:17",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "ItemﾠdeﾠConfiguração",
    Sintoma: "CriarﾠItemﾠdeﾠConfiguraçãoﾠ–ﾠAplicações",
    Grupoﾠdeﾠatribuição: "N2-ATIVOS-IC",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ11:07:17",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "ItemﾠdeﾠConfiguração",
    ComentáriosﾠVisiveisﾠ: "Planilhaﾠenviadaﾠcomﾠinformaçõesﾠsolicitadas",
    Resolução: "RaealizadoﾠaﾠcriaçãoﾠdasﾠIcsﾠsolicitadas.",
  },
  {
    Número: "TASK0948363",
    Aberto: "26/04/2024ﾠ14:36:09",
    Atualizadoﾠem: "01/05/2024ﾠ17:06:56",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "4/26/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "RevogaçãoﾠdeﾠAcesso",
    Sintoma: "RevogaçãoﾠdeﾠAcesso",
    QualificaçãoﾠSintoma: "SemﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "01/05/2024ﾠ17:06:56",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "RevogaçãoﾠdeﾠAcesso",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Realizadoﾠaﾠrevogaçãoﾠdosﾠacessosﾠconformeﾠsolicitado",
  },
  {
    Número: "TASK0948365",
    Aberto: "26/04/2024ﾠ14:39:07",
    Atualizadoﾠem: "03/05/2024ﾠ09:35:45",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "Acessos",
    SubcategoriaﾠRelatório: "LiberaçãoﾠdeﾠAcesso",
    Sintoma: "ReativaçãoﾠdeﾠAcessos",
    QualificaçãoﾠSintoma: "ComﾠSAP",
    Grupoﾠdeﾠatribuição: "N1-ACESSOS-SAP",
    Categoria: "Acesso",
    Atribuídoﾠa: "AnalistaﾠAcessoﾠ",
    Prioridade: "2ﾠ-ﾠMédio",
    Encerrado: "03/05/2024ﾠ08:05:24",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "LiberaçãoﾠdeﾠAcesso",
    ComentáriosﾠVisiveisﾠ: "Realizadoﾠenvioﾠdasﾠinformaçõesﾠsolicitadas",
    Resolução: "Usuárioﾠdeﾠredeﾠcriadoﾠeﾠenviadoﾠosﾠdadosﾠaoﾠgestorﾠimediato",
  },
  {
    Número: "TASK0948800",
    Aberto: "29/04/2024ﾠ09:29:21",
    Atualizadoﾠem: "02/05/2024ﾠ10:00:14",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "SolicitaçãoﾠdeﾠEquipamento",
    Sintoma: "ColaboradorﾠInterno",
    QualificaçãoﾠSintoma: "CapitaisﾠeﾠRegiõesﾠMetropolitanas",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ10:00:14",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "SolicitaçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "Equipamentosﾠliberadosﾠparaﾠentrega",
    Resolução: "Equipamentosﾠentregueﾠeﾠtermosﾠassinados",
  },
  {
    Número: "TASK0948949",
    Aberto: "29/04/2024ﾠ11:15:10",
    Atualizadoﾠem: "03/05/2024ﾠ13:43:13",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "Handsﾠon",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ13:43:14",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Solicitoﾠnovoﾠpontoﾠdeﾠrede",
    ComentáriosﾠVisiveisﾠ: "Aguardandoﾠpassagemﾠdoﾠcabeamento",
    Resolução: "Pontosﾠcriadosﾠeﾠativados",
  },
  {
    Número: "TASK0950427",
    Aberto: "02/05/2024ﾠ05:37:17",
    Atualizadoﾠem: "03/05/2024ﾠ00:34:26",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "ServiçosﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Infraestruturaﾠ-ﾠSoluções",
    Sintoma: "InstalaçãoﾠdeﾠAplicativos",
    QualificaçãoﾠSintoma: "SuporteﾠaﾠInstalaçãoﾠeﾠConfiguraçãoﾠdeﾠAplicativos",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ00:34:26",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Solicitoﾠnovoﾠpontoﾠdeﾠrede",
    ComentáriosﾠVisiveisﾠ: "Aguardandoﾠpassagemﾠdoﾠcabeamento",
    Resolução: "Pontosﾠcriadosﾠeﾠativados",
  },
  {
    Número: "TASK0950560",
    Aberto: "02/05/2024ﾠ09:02:47",
    Atualizadoﾠem: "02/05/2024ﾠ15:13:57",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "ControleﾠdeﾠAcessoﾠeﾠRelógioﾠdeﾠPonto",
    Sintoma: "Suporte",
    QualificaçãoﾠSintoma: "Porta",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ15:13:57",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "ControleﾠdeﾠAcessoﾠeﾠRelógioﾠdeﾠPonto",
    ComentáriosﾠVisiveisﾠ: "Porﾠfavorﾠinformarﾠlocalﾠ",
    Resolução: "Realizadoﾠrestartﾠdoﾠserviçoﾠlocalﾠ",
  },
  {
    Número: "TASK0950674",
    Aberto: "02/05/2024ﾠ09:43:30",
    Atualizadoﾠem: "02/05/2024ﾠ13:03:35",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "ControleﾠdeﾠAcessoﾠeﾠRelógioﾠdeﾠPonto",
    Sintoma: "Suporte",
    QualificaçãoﾠSintoma: "REP",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ13:03:35",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "ControleﾠdeﾠAcessoﾠeﾠRelógioﾠdeﾠPonto",
    ComentáriosﾠVisiveisﾠ: "Porﾠfavorﾠinformarﾠlocalﾠ",
    Resolução: "Realizadoﾠrestartﾠdoﾠserviçoﾠlocalﾠ",
  },
  {
    Número: "TASK0950875",
    Aberto: "02/05/2024ﾠ11:33:41",
    Atualizadoﾠem: "02/05/2024ﾠ16:30:38",
    EstadoﾠRelatório: "Fechado",
    ResolvidoﾠRelatório: "5/2/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "DocNix",
    Sintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "02/05/2024ﾠ16:30:36",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Fábricaﾠ1",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "TASK0951510",
    Aberto: "03/05/2024ﾠ08:37:13",
    Atualizadoﾠem: "03/05/2024ﾠ09:57:23",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "Dynamics",
    Sintoma: "AuditoriaﾠInterna",
    QualificaçãoﾠSintoma: "Outros",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ09:57:23",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "TASK0951667",
    Aberto: "03/05/2024ﾠ09:44:47",
    Atualizadoﾠem: "03/05/2024ﾠ09:49:36",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "AtivarﾠPontoﾠdeﾠRede",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ09:49:36",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Somenteﾠnaﾠminhaﾠmaquina",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠsistemaﾠoperacionalﾠlocalﾠ",
  },
  {
    Número: "TASK0951715",
    Aberto: "03/05/2024ﾠ10:04:45",
    Atualizadoﾠem: "03/05/2024ﾠ17:17:11",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "OutrosﾠSistemas",
    SubcategoriaﾠRelatório: "HCA",
    Sintoma: "Dúvida",
    QualificaçãoﾠSintoma: "Informação",
    Grupoﾠdeﾠatribuição: "N2-LEG-SAT",
    Categoria: "AMS-NãoﾠSAP",
    Atribuídoﾠa: "AnalistaﾠAMS",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ17:17:11",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "Escritórioﾠcentral",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0951951",
    Aberto: "03/05/2024ﾠ12:55:09",
    Atualizadoﾠem: "03/05/2024ﾠ13:18:47",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "SolicitaçãoﾠdeﾠNFﾠEntrada\\Saída",
    Grupoﾠdeﾠatribuição: "N2-AT-EXTERNOS",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ12:59:36",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0951957",
    Aberto: "03/05/2024ﾠ13:02:51",
    Atualizadoﾠem: "03/05/2024ﾠ13:18:29",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "SolicitaçãoﾠdeﾠNFﾠEntrada\\Saída",
    Grupoﾠdeﾠatribuição: "N2-AT-EXTERNOS",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ13:06:37",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "Sistemaﾠlento",
    ComentáriosﾠVisiveisﾠ: "Emﾠtodoﾠdepartamento",
    Resolução: "SoluçãoﾠaplicadaﾠReinciadoﾠserviçoﾠdatabase",
  },
  {
    Número: "TASK0951959",
    Aberto: "03/05/2024ﾠ13:06:27",
    Atualizadoﾠem: "03/05/2024ﾠ13:34:03",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "Impressoras",
    SubcategoriaﾠRelatório: "SuporteﾠImpressoras",
    Sintoma: "TrocaﾠdeﾠToner",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ13:34:03",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "SuporteﾠImpressoras",
    ComentáriosﾠVisiveisﾠ: "informarﾠlocalﾠdaﾠimpressora?",
    Resolução: "Realizadoﾠaﾠretiradaﾠdosﾠpapeisﾠatolados",
  },
  {
    Número: "TASK0951964",
    Aberto: "03/05/2024ﾠ13:15:34",
    Atualizadoﾠem: "03/05/2024ﾠ13:18:10",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "SolicitaçãoﾠdeﾠNFﾠEntrada\\Saída",
    Grupoﾠdeﾠatribuição: "N2-AT-EXTERNOS",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ13:18:10",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "ConfiguraçãoﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "informarﾠmelhorﾠhorárioﾠparaﾠatendimentoﾠ",
    Resolução: "Realizadoﾠaﾠconfiguraçãoﾠdoﾠsmartphoneﾠconformeﾠsolicitado",
  },
  {
    Número: "TASK0951989",
    Aberto: "03/05/2024ﾠ13:51:37",
    Atualizadoﾠem: "03/05/2024ﾠ13:53:26",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "EquipamentoﾠdeﾠTI",
    SubcategoriaﾠRelatório: "Handsﾠon",
    Sintoma: "TransferênciaﾠdeﾠEquipamento",
    Grupoﾠdeﾠatribuição: "N2-FS-NA",
    Categoria: "Ativos",
    Atribuídoﾠa: "AnalistaﾠServiceﾠDesk",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ13:53:26",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "TransferênciaﾠdeﾠEquipamento",
    ComentáriosﾠVisiveisﾠ: "Informaçãoﾠanxeadaﾠconformeﾠsolicitado",
    Resolução: "Notaﾠdeﾠsaidaﾠanexadaﾠeﾠenviadaﾠparaﾠseguirﾠcomﾠtransferencia",
  },
  {
    Número: "TASK0952138",
    Aberto: "03/05/2024ﾠ15:52:12",
    Atualizadoﾠem: "03/05/2024ﾠ16:26:54",
    EstadoﾠRelatório: "Resolvido",
    ResolvidoﾠRelatório: "5/3/24",
    CategoriaﾠRelatório: "SuporteﾠaﾠEquipamento",
    SubcategoriaﾠRelatório: "RoamingﾠInternacional",
    Sintoma: "LiberaçãoﾠdeﾠRoamingﾠInternacional",
    Grupoﾠdeﾠatribuição: "TELEFONIA",
    Categoria: "FieldﾠService",
    Atribuídoﾠa: "AnalistaﾠField",
    Prioridade: "3ﾠ-ﾠBaixo",
    Encerrado: "03/05/2024ﾠ16:26:54",
    SolicitanteﾠTarefa: "ADMﾠSistemas",
    Local: "CentroﾠdeﾠDistribuição",
    Descrição: "RoamingﾠInternacional",
    ComentáriosﾠVisiveisﾠ: "Dataﾠinformadasﾠconformeﾠsolicitado",
    Resolução:
      "AtivaçãoﾠdoﾠRoamingﾠInternacionalﾠconcluidaﾠconformeﾠsolicitado",
  },
];

export default data;
